#- name: Install prerequisites
#  apt: name=aptitude update_cache=yes state=latest force_apt_get=yes
#  tags: [ system ]

- name: Install LAMP Packages
  apt: name={{ item }} update_cache=yes state=latest
  loop: [ 'python3-pymysql' ]
  tags: [ system ]

